/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controladores.AsistenciaControlador;
import modelos.Asistencia;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ever Vásquez
 */
public class jpAsistentes extends javax.swing.JPanel {

    /**
     * Creates new form jpAsistentes
     */
    public jpAsistentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsistentes = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(88, 88, 160));

        tblAsistentes.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblAsistentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CARNET", "AÑO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAsistentes);
        if (tblAsistentes.getColumnModel().getColumnCount() > 0) {
            tblAsistentes.getColumnModel().getColumn(0).setResizable(false);
            tblAsistentes.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblAsistentes.getColumnModel().getColumn(1).setResizable(false);
            tblAsistentes.getColumnModel().getColumn(1).setPreferredWidth(150);
            tblAsistentes.getColumnModel().getColumn(2).setResizable(false);
            tblAsistentes.getColumnModel().getColumn(2).setPreferredWidth(20);
            tblAsistentes.getColumnModel().getColumn(3).setResizable(false);
            tblAsistentes.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("ASISTENTES DE: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(82, 82, 82)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cargarAsistentes(int idTaller){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel)tblAsistentes.getModel();
        modelo.setRowCount(0);//Limpia todas los registros de la tabla (Basicamente le indica que no quiere ninguna fila)
        AsistenciaControlador controlador = new AsistenciaControlador();
        List<Asistencia> lstAsistencia = controlador.getLisTalleresPonencias();
        String nombre = "";
        for (Asistencia item : lstAsistencia){
            if (idTaller == item.getIdTallerponencia().getIdTallerponencia()) {
                nombre =  item.getIdTallerponencia().getNombre().toString();
                int annio = item.getIdEstudiante().getAnnioCarrera();
                String anio = "";
                switch (annio){
                    case 1 -> anio = "Primer año.";
                    case 2 -> anio = "Segundo año.";
                    case 3 -> anio = "Tercer año.";
                    case 4 -> anio = "Cuarto año.";
                    case 5 -> anio = "Quinto año.";
                }
                modelo.addRow(new Object[]{item.getIdEstudiante().getIdEstudiante(), item.getIdEstudiante().getNombresApellidos(), item.getIdEstudiante().getCarnet(), anio});   
            }
        }
        
        lblTitulo.setText(lblTitulo.getText() + nombre);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblAsistentes;
    // End of variables declaration//GEN-END:variables
}
