/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controladores.AsistenciaControlador;
import controladores.TalleresPonenciasControlador;
import modelos.Asistencia;
import modelos.Talleresponencias;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ever Vásquez
 */
public class jpEstaditicas extends javax.swing.JPanel {

    /**
     * Creates new form jpEstaditicas
     */
    
    private int idTaller = -1;
    
    public jpEstaditicas() {
        initComponents();
        cargardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstadisticas = new javax.swing.JTable();
        btnVerAsistentes = new javax.swing.JButton();

        setBackground(new java.awt.Color(88, 88, 160));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ESTADISTICAS DE TALLERES - PONENCIAS");

        tblEstadisticas.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TITULO", "ENCARGADO", "LUGAR", "TOTAL ASISTENTES"
            }
        ));
        tblEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstadisticasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstadisticas);
        if (tblEstadisticas.getColumnModel().getColumnCount() > 0) {
            tblEstadisticas.getColumnModel().getColumn(0).setResizable(false);
            tblEstadisticas.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblEstadisticas.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblEstadisticas.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblEstadisticas.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        btnVerAsistentes.setBackground(new java.awt.Color(28, 109, 66));
        btnVerAsistentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/lista-de-asistentes.png"))); // NOI18N
        btnVerAsistentes.setText("VER ASISTENTES");
        btnVerAsistentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerAsistentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAsistentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 152, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(108, 108, 108)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnVerAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerAsistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAsistentesActionPerformed
        // TODO add your handling code here:
        
        if (idTaller != -1) {
            btnVerAsistentes.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            jpAsistentes panel = new jpAsistentes();
            panel.cargarAsistentes(idTaller);
            panel.setSize(this.getWidth(), this.getHeight());
            panel.setLocation(0, 0);
            this.removeAll();
            this.add(panel, BorderLayout.CENTER);
            this.revalidate();
            this.repaint();
            btnVerAsistentes.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
        else{
            JOptionPane.showMessageDialog(null, "ASEGURESE DE HABER SELECCIONADO EL RESGISTRO DEL QUE DESEA VER LOS ASISTENTES.","ERROR.", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnVerAsistentesActionPerformed

    private void tblEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstadisticasMouseClicked
        // TODO add your handling code here:
        idTaller = Integer.parseInt(tblEstadisticas.getValueAt(tblEstadisticas.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_tblEstadisticasMouseClicked

    private void cargardatos(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel)tblEstadisticas.getModel();
        modelo.setRowCount(0);//Limpia todas los registros de la tabla (Basicamente le indica que no quiere ninguna fila)
        TalleresPonenciasControlador controlador = new TalleresPonenciasControlador();
        List<Talleresponencias> lstPonencias = controlador.getLisTalleresPonencias();
        //jpNuevoEstudiante.
        for (Talleresponencias item : lstPonencias) {
            int asis = totalAsistencia(item.getIdTallerponencia());
            modelo.addRow(new Object[]{item.getIdTallerponencia(), item.getNombre(), item.getNombreEncargado(), item.getLugar(), asis});
        }
    }
    
    private int totalAsistencia(int idTaller){
        int tAsis = 0;
        AsistenciaControlador controlador1 = new AsistenciaControlador();
        List<Asistencia> lstAsistencia = controlador1.getLisTalleresPonencias();
        
        for (Asistencia item : lstAsistencia){
            if (idTaller == item.getIdTallerponencia().getIdTallerponencia()) {
                tAsis ++;
            }
        }
        return tAsis;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerAsistentes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEstadisticas;
    // End of variables declaration//GEN-END:variables
}
