/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controladores.AsistenciaControlador;
import controladores.EstudianteControlador;
import controladores.TalleresPonenciasControlador;
import modelos.Asistencia;
import modelos.Estudiantes;
import modelos.Talleresponencias;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Ever Vásquez
 */
public class jpInscribir extends javax.swing.JPanel {

    /**
     * Creates new form jpInscribir
     */
    public jpInscribir() {
        initComponents();
        cargarEstudiantes();
        cargarTalleresPonencias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbEstudiantes = new javax.swing.JComboBox();
        cmbTalleresPonencias = new javax.swing.JComboBox();
        btnInscribirEstudiante = new javax.swing.JButton();

        setBackground(new java.awt.Color(88, 88, 160));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSCRIBIR A TALLER - PONENCIA");

        cmbEstudiantes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione el estudiante:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        cmbTalleresPonencias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione el taller o ponencia:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        btnInscribirEstudiante.setBackground(new java.awt.Color(28, 109, 66));
        btnInscribirEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/edit.png"))); // NOI18N
        btnInscribirEstudiante.setText("Inscribir");
        btnInscribirEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbTalleresPonencias, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInscribirEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addComponent(cmbEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(cmbTalleresPonencias, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnInscribirEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirEstudianteActionPerformed
        // TODO add your handling code here:
        if (!(("Seleccione el estudiante...".equals(cmbEstudiantes.getSelectedItem()) || ("Seleccione el taller o ponencia...".equals(cmbTalleresPonencias.getSelectedItem()))))) {
            Asistencia nuevaAsistencia = new Asistencia();
            nuevaAsistencia.setIdEstudiante((Estudiantes)cmbEstudiantes.getSelectedItem());
            nuevaAsistencia.setIdTallerponencia((Talleresponencias)cmbTalleresPonencias.getSelectedItem());

            AsistenciaControlador controlador = new AsistenciaControlador();
            controlador.insertarAsistencia(nuevaAsistencia);
            JOptionPane.showMessageDialog(null, "EL ESTUDIANTE FUE INSCRITO EXITOSAMENTE.","ESTUDIANTE INSCRITO.", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        }
        else {
            JOptionPane.showMessageDialog(null, "ASEGURESE DE HABER LLENADO COMPLETMENTE EL FORMULARIO.","ERROR.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInscribirEstudianteActionPerformed
    
    public void cargarEstudiantes(){
        EstudianteControlador controlador = new EstudianteControlador();
        List<Estudiantes> lstEstudiantes = controlador.getLisEstudiantes();
        cmbEstudiantes.addItem("Seleccione el estudiante...");
        for (Estudiantes item: lstEstudiantes) {
            cmbEstudiantes.addItem(item);
        }
    }
    
    public void cargarTalleresPonencias(){
        TalleresPonenciasControlador controlador = new TalleresPonenciasControlador();
        List<Talleresponencias> lstTalleresPonencias = controlador.getLisTalleresPonencias();
        cmbTalleresPonencias.addItem("Seleccione el taller o ponencia...");
        for (Talleresponencias item : lstTalleresPonencias) {
            cmbTalleresPonencias.addItem(item);
        }
    }
    
    public void limpiar(){
        cmbTalleresPonencias.setSelectedItem("SSeleccione el taller o ponencia...");
        cmbEstudiantes.setSelectedItem("Seleccione el estudiante...");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscribirEstudiante;
    private javax.swing.JComboBox cmbEstudiantes;
    private javax.swing.JComboBox cmbTalleresPonencias;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
