/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controladores.AsistenciaControlador;
import controladores.EstudianteControlador;
import modelos.Asistencia;
import modelos.Estudiantes;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ever Vásquez
 */
public class jpNuevoEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form jpNuevoEstudiante
     */
    public jpNuevoEstudiante() {
        initComponents();
        cargarEstudiantes();
        this.txtIdEstudiante.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        txtNombreEstudiante = new javax.swing.JTextField();
        txtCarnetEstudiante = new javax.swing.JTextField();
        cmbAnniosCarrera = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtIdEstudiante = new javax.swing.JTextField();

        setBackground(new java.awt.Color(88, 88, 160));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("AGREGAR ESTUDIANTE");

        txtNombreEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre completo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        txtCarnetEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carnet:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        cmbAnniosCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Primer año.", "Segundo año.", "Tercer año.", "Cuarto año.", "Quinto año." }));
        cmbAnniosCarrera.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Año de carrera:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        btnGuardar.setBackground(new java.awt.Color(28, 109, 66));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/blanco.png"))); // NOI18N
        btnGuardar.setText("GUARDAR REGISTRO");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tblEstudiantes.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE COMPLETO", "CARNET", "AÑO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstudiantes);
        if (tblEstudiantes.getColumnModel().getColumnCount() > 0) {
            tblEstudiantes.getColumnModel().getColumn(0).setResizable(false);
            tblEstudiantes.getColumnModel().getColumn(0).setPreferredWidth(5);
            tblEstudiantes.getColumnModel().getColumn(1).setResizable(false);
            tblEstudiantes.getColumnModel().getColumn(1).setPreferredWidth(180);
            tblEstudiantes.getColumnModel().getColumn(2).setResizable(false);
            tblEstudiantes.getColumnModel().getColumn(2).setPreferredWidth(40);
            tblEstudiantes.getColumnModel().getColumn(3).setResizable(false);
            tblEstudiantes.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        btnEditar.setBackground(new java.awt.Color(23, 173, 235));
        btnEditar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/edit.png"))); // NOI18N
        btnEditar.setText("EDITAR REGISTRO");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(76, 8, 8));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bin.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR REGISTRO");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtIdEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbAnniosCarrera, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCarnetEstudiante, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(336, 336, 336))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCarnetEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAnniosCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (!(("".equals(txtNombreEstudiante.getText())) || ("".equals(txtCarnetEstudiante.getText())) || ("Seleccione...".equals(cmbAnniosCarrera.getSelectedItem())))) {
            Estudiantes nuevoEstudiante = new Estudiantes();
            nuevoEstudiante.setNombresApellidos(txtNombreEstudiante.getText());
            nuevoEstudiante.setCarnet(txtCarnetEstudiante.getText());
            String annio = cmbAnniosCarrera.getSelectedItem().toString();
            int anio = 0;
            switch (annio){
                case "Primer año." -> anio = 1;
                case "Segundo año." -> anio = 2;
                case "Tercer año." -> anio = 3;
                case "Cuarto año." -> anio = 4;
                case "Quinto año." -> anio = 5;
            }
            nuevoEstudiante.setAnnioCarrera(anio);
            EstudianteControlador controlador = new EstudianteControlador();
            controlador.insertarEstudiante(nuevoEstudiante);
            JOptionPane.showMessageDialog(null, "EL REGISTRO FUE INSERTADO EXITOSAMENTE.","REGISTRO INSERTADO.", JOptionPane.INFORMATION_MESSAGE);
            limpiarTodo();
            cargarEstudiantes();
        }
        else{
            JOptionPane.showMessageDialog(null, "ASEGURESE DE HABER LLENADO COMPLETMENTE EL FORMULARIO.","ERROR.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstudiantesMouseClicked
        // TODO add your handling code here:
        String id = tblEstudiantes.getValueAt(tblEstudiantes.getSelectedRow(), 0).toString();
        String nombre = tblEstudiantes.getValueAt(tblEstudiantes.getSelectedRow(), 1).toString();
        String carnet = tblEstudiantes.getValueAt(tblEstudiantes.getSelectedRow(), 2).toString();
        String annio = tblEstudiantes.getValueAt(tblEstudiantes.getSelectedRow(), 3).toString();
        txtIdEstudiante.setText(id);
        txtNombreEstudiante.setText(nombre);
        txtCarnetEstudiante.setText(carnet);
        cmbAnniosCarrera.setSelectedItem(annio);
    }//GEN-LAST:event_tblEstudiantesMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        limpiarTodo();
    }//GEN-LAST:event_formMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (!(("".equals(txtNombreEstudiante.getText())) || ("".equals(txtCarnetEstudiante.getText())) || ("Seleccione...".equals(cmbAnniosCarrera.getSelectedItem())))) {
            Estudiantes estudianteEdit = new Estudiantes();
            estudianteEdit.setIdEstudiante(Integer.parseInt(txtIdEstudiante.getText()));
            estudianteEdit.setNombresApellidos(txtNombreEstudiante.getText());
            estudianteEdit.setCarnet(txtCarnetEstudiante.getText());
            String annio = cmbAnniosCarrera.getSelectedItem().toString();
            int anio = 0;
            switch (annio){
                case "Primer año." -> anio = 1;
                case "Segundo año." -> anio = 2;
                case "Tercer año." -> anio = 3;
                case "Cuarto año." -> anio = 4;
                case "Quinto año." -> anio = 5;
            }
            estudianteEdit.setAnnioCarrera(anio);
            
            EstudianteControlador controlador = new EstudianteControlador();
            controlador.editarEstudiante(estudianteEdit);
            JOptionPane.showMessageDialog(null, "EL REGISTRO SE ACTUALIZÓ EXITOSAMENTE.","REGISTRO ACTUALIZADO.", JOptionPane.INFORMATION_MESSAGE);
            limpiarTodo();
            cargarEstudiantes();
        }
        else{
            JOptionPane.showMessageDialog(null, "ASEGURESE DE HABER SELECCIONADO EL RESGISTRO QUE DESEA EDITAR.","ERROR.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if (!(("".equals(txtNombreEstudiante.getText())) || ("".equals(txtCarnetEstudiante.getText())) || ("Seleccione...".equals(cmbAnniosCarrera.getSelectedItem())))) {
            int verificar = JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO QUE DESEA ELIMINAR EL REGISTRO?", "CONFIRME.", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (verificar == JOptionPane.YES_OPTION){
                int idElim = Integer.parseInt(txtIdEstudiante.getText());
                //Busca los talleres a los que asiste el estudiante para eliminar esos registros
                buscarCursoAsistido(idElim);
                EstudianteControlador controlador = new EstudianteControlador();
                controlador.eliminarEstudiante(idElim);
                JOptionPane.showMessageDialog(null, "EL REGISTRO FUE ELIMINADO EXITOSAMENTE.","REGISTRO ELIMINADO.", JOptionPane.INFORMATION_MESSAGE);
                limpiarTodo();
                cargarEstudiantes();
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "ASEGURESE DE HABER SELECCIONADO EL RESGISTRO QUE DESEA ELIMINAR.","ERROR.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cargarEstudiantes(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel)tblEstudiantes.getModel();
        modelo.setRowCount(0);//Limpia todas los registros de la tabla (Basicamente le indica que no quiere ninguna fila)
        EstudianteControlador controlador = new EstudianteControlador();
        List<Estudiantes> lstEstudiantes = controlador.getLisEstudiantes();
        //jpNuevoEstudiante.
        for (Estudiantes item : lstEstudiantes) {
            int annio = item.getAnnioCarrera();
            String anio = "";
            switch (annio){
                case 1 -> anio = "Primer año.";
                case 2 -> anio = "Segundo año.";
                case 3 -> anio = "Tercer año.";
                case 4 -> anio = "Cuarto año.";
                case 5 -> anio = "Quinto año.";
            }
            modelo.addRow(new Object[]{item.getIdEstudiante(), item.getNombresApellidos(), item.getCarnet(), anio});
        }
    }
    
    private void buscarCursoAsistido(int idEstudiante){
        AsistenciaControlador controlador1 = new AsistenciaControlador();
        List<Asistencia> lstAsistencia = controlador1.getLisTalleresPonencias();
        List<Integer> idAsistencia = new ArrayList<Integer>();
        int i = 0;
        for (Asistencia item : lstAsistencia) {
            if (idEstudiante == item.getIdEstudiante().getIdEstudiante()) {
                idAsistencia.add(item.getIdAsistencia());
            }
            i ++;
        }
        
        for (int j : idAsistencia) {
            AsistenciaControlador controlador = new AsistenciaControlador();
            controlador.eliminarAsistencia(j);
        }
        
    }
    
    private void limpiarTodo(){
        txtIdEstudiante.setText("");
        txtNombreEstudiante.setText("");
        txtCarnetEstudiante.setText("");
        cmbAnniosCarrera.setSelectedItem("Seleccione...");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbAnniosCarrera;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtCarnetEstudiante;
    private javax.swing.JTextField txtIdEstudiante;
    private javax.swing.JTextField txtNombreEstudiante;
    // End of variables declaration//GEN-END:variables
}
